### ISSUE TITLE
Error on detection layer~ can u fix it?

### ISSUE THREAD

**Issue by KirtoXX** [parap1uie-s/Keras-RFCN#1]
Traceback (most recent call last):
  File "D:/Keras-RFCN-master/Fashion_Test.py", line 138, in <module>
    model_dir=os.path.join(ROOT_DIR, "logs") )
  File "D:\Keras-RFCN-master\KerasRFCN\Model\Model.py", line 42, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "D:\Keras-RFCN-master\KerasRFCN\Model\Model.py", line 184, in build
    [rpn_rois, classify_output, regr_output, input_image_meta])
  File "C:\Anaconda3\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\Keras-RFCN-master\KerasRFCN\Model\Model.py", line 836, in call
    self.config.IMAGES_PER_GPU)
  File "D:\Keras-RFCN-master\KerasRFCN\Utils.py", line 620, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "D:\Keras-RFCN-master\KerasRFCN\Model\Model.py", line 835, in <lambda>
    lambda x, y, w, z: refine_detections_graph(x, y, w, z, self.config),
  File "D:\Keras-RFCN-master\KerasRFCN\Model\Model.py", line 722, in refine_detections_graph
    rois, deltas_specific * config.BBOX_STD_DEV)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 1000 and 4 for 'mrcnn_detection/mul' (op: 'Mul') with input shapes: [1000], [4].

**Comment by parap1uie-s** [comment]
This error looks strange. But I will check it.
Would you provide more information? 

- Did you use the project on your own dataset? 

- Your Config?

**Comment by Lakshaysharma048** [comment]
Hi @parap1uie-s ,

I am also getting the same error in Fashion_Test.py (Dimension must be equal)

I have used my dataset and Config is same as provided.

Also, is there a way of saving the model with the weight instead of saving just the weights.

**Comment by parap1uie-s** [comment]
Bug fixed, issue close.

**Comment by bhargav-aai** [comment]
@parap1uie-s, Have you added the feature to save a model with its weights?
