### ISSUE TITLE
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

### ISSUE THREAD

**Issue by cpoptic** [parap1uie-s/Keras-RFCN#8]
running >> python Fashion_Train.py
produces the following error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "Fashion_Train.py", line 124, in <module>
    model = RFCN_Model(mode="training", config=config, model_dir=os.path.join(ROOT_DIR, "logs") )
  File "/data/repos/Keras-RFCN/KerasRFCN/Model/Model.py", line 42, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/data/repos/Keras-RFCN/KerasRFCN/Model/Model.py", line 77, in build
    P2, P3, P4, P5, P6 = ResNet(input_image, architecture=config.BACKBONE).output_layers
  File "/data/repos/Keras-RFCN/KerasRFCN/Model/ResNet.py", line 23, in __init__
    self.construct_graph(input_tensor)
  File "/data/repos/Keras-RFCN/KerasRFCN/Model/ResNet.py", line 28, in construct_graph
    x = KL.ZeroPadding2D((3, 3))(input_tensor)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 796, in __call__
    inputs, outputs, args, kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 908, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1089, in _add_inbound_node
    arguments=arguments)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1760, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

**Comment by chengjaun** [comment]
Now I have the same error, have you solved this problem?
